### ISSUE TITLE
Form input focus - label not moving away

### ISSUE THREAD

**Issue by s1lviu** [mdbootstrap/Admin-Dashboard-Template-Angular-Bootstrap#1]
Hello!

I tried to do some forms in your template, but there is a input problem: <img src="https://i.imgur.com/z8W60PR.png">
For the form I used the code from [here](https://mdbootstrap.com/angular/forms/forms/).

**Comment by Bloodcast69** [comment]
Dear @s1lviu,
Still need help? Let me know.
Best Regards,
Damian

**Comment by s1lviu** [comment]
Hi, @Bloodcast69 
Post the solution here, if you know how to get it right
Thank you!

**Comment by Bloodcast69** [comment]
Today I updated this Admin Template. Please update your app to latest 6.0.2 version and try one more time. 

You have to use mdbInputDirective on your inputs for moving away label. But mdbInputDirective was added in MDB Angular 6.0.0. In older version, you have to use mdbActive directive.

**Comment by s1lviu** [comment]
Good to know then. 
PS: Is this template ok for production use?

**Comment by Bloodcast69** [comment]
Yes, why not? It's complete template, but free. If you're looking for more advanced template, please check our Angular Admin Template Pro - https://mdbootstrap.com/product/angular-admin-theme/

**Comment by s1lviu** [comment]
> Yes, why not?

Because of bugs or some important missing features like this described in the issue.

> It's complete template, but free. If you're looking for more advanced
> template, please check our Angular Admin Template Pro -
> [https://mdbootstrap.com/product/angular-admin-theme/](https://mdbootstrap.com/product/angular-admin-theme/)

I have a small project and I'm interested in something free for the moment. I know the pro version, thanks!
