### ISSUE TITLE
failed to compile - ".../rxjs/Observable" has no exported member 'Observable'

### ISSUE THREAD

**Issue by coyu1314** [mdbootstrap/Admin-Dashboard-Template-Angular-Bootstrap#2]
This is the first time I try this admin-dashboard template. and I got bunch of complains about the observable when I did ng serve. All I did was just 
1. clone this repo 
2. npm install 
3. run ng serve -o 

Then I got the following complains about the observable. Any idea what's going on? thanks

`ERROR in node_modules/@agm/core/services/google-maps-api-wrapper.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/circle-manager.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/data-layer-manager.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/info-window-manager.d.ts(1,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/kml-layer-manager.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/marker-manager.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/polygon-manager.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@agm/core/services/managers/polyline-manager.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/angular-calendar/dist/esm/src/components/day/calendarDayView.component.d.ts(3,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/dist/esm/src/components/day/calendarDayView.component.d.ts(4,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angular-calendar/dist/esm/src/components/month/calendarMonthView.component.d.ts(3,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/dist/esm/src/components/month/calendarMonthView.component.d.ts(4,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angular-calendar/dist/esm/src/components/week/calendarWeekView.component.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/dist/esm/src/components/week/calendarWeekView.component.d.ts(3,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angular-resizable-element/dist/esm/src/resizable.directive.d.ts(2,10): error TS2305: Module '"/Users/home.imac/Desktop/code/ng2/ng6mdb3/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.
node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.`

**Comment by coyu1314** [comment]
ok. found the solution. it looks like rxjs-compat is missing. just do  `npm i rxjs-compat` right after `npm install` then do `ng serve -o`

**Comment by RahulShalgar** [comment]
I was facing the same problem... now this helped me.. Thanks a lot..

**Comment by pabloroxo** [comment]
@coyu1314 is a lifesaver! thanks!

**Comment by sudiptosen** [comment]
lifesaver+

**Comment by roblawford** [comment]
Thank you! Lifesaver +100

**Comment by moldovans** [comment]
don't however, let this page to be infinite with your looping comments "livesaver++"

**Comment by TanjillaTina** [comment]
Project Saver!!
Thanks 
<3 @coyu1314

**Comment by antalmate12** [comment]
lifesaver++

**Comment by Oussemabj** [comment]
thank you <3

**Comment by sunandpujari** [comment]
Thank you!!!!!!!!!

**Comment by akumartiwari** [comment]
Thank you! Lifesaver +1000

**Comment by kaidgg** [comment]
lifesaver++

**Comment by jakett** [comment]
With rxjs 6.5.2 --> 
import { Observable } from 'rxjs/internal/Observable';

**Comment by purnimadas27** [comment]
Thank you!!!

**Comment by moldovans** [comment]
```
while (true) {
    livesaver++;
}
```

**Comment by subhamsaha-manu** [comment]
Thank you!!!

**Comment by serhioV** [comment]
> Thank you!!!

what a idiot

**Comment by moldovans** [comment]
I see all Indians are a little bit spammers... "Thankyou!, livesaver!, oh what great!, is crazy! oh my god!"

**Comment by harshal8888** [comment]
thank u lifesaver

**Comment by hgaragao** [comment]
Thank you lifesaver+

**Comment by krupakheti** [comment]
Thank you !\++

**Comment by arsalan-mahmood** [comment]
> With rxjs 6.5.2 -->
> import { Observable } from 'rxjs/internal/Observable';

It worked, thanks man

**Comment by Kartik618** [comment]
> ok. found the solution. it looks like rxjs-compat is missing. just do `npm i rxjs-compat` right after `npm install` then do `ng serve -o`

thanks

**Comment by rahianeja** [comment]
`npm i rxjs-compat ` Worked for me too !!! Thanks ++

**Comment by ghost** [comment]
u can also solve this issue by update angular-in-memory web api
npm i angular-in-memory-web-api@0.8.0

**Comment by ajay-lingayat** [comment]
@coyu1314  a million thanks to you!

**Comment by andyyapwl** [comment]
omg, amazing!, thanks!
