### ISSUE TITLE
Error while doing npm i

### ISSUE THREAD

**Issue by ancgate** [mdbootstrap/Admin-Dashboard-Template-Angular-Bootstrap#3]
Unhandled rejection Error: Integrity check failed:er-api-error: sill pacote trying angular-bootstrap-md@file:angular-bootstrap-md-6.2.2.tgz by hash: sha512-H7vhYx+HqIC7KPp06buCZAm6snUV6sCJwM3oLV
  Wanted: sha512-H7vhYx+HqIC7KPp06buCZAm6snUV6sCJwM3oLV7BPlPyl5yQGJd6DHk7Vt4qyzUOEvCUsWXRtYA38basbX/Qtg==
   Found: sha512-mmXdle2qlSUn0fFL0hF98Ou9s+UkbFK2ggdPWW9/ErbwzzGQOKQxnet5OQTQpM5So6AQqn/w5Y0DsRl2E/O2iw==

**Comment by Bloodcast69** [comment]
Dear ancgate,
Sorry for so long response time. Remove package-lock.json file and try one more time - now it should work fine.
Best Regards,
Damian
