### ISSUE TITLE
The dashboard (left) cannot be accessed in mobile view..!

### ISSUE THREAD

**Issue by SachienRaj** [mdbootstrap/Admin-Dashboard-Template-Angular-Bootstrap#4]

**Comment by Bloodcast69** [comment]
@SachienRaj 
Please provide me with a detailed description of your problem. Without it, I won't be able to help you well.

**Comment by SachienRaj** [comment]
When the Web app is in mobile view or the browser window size is decreased, the left navigation bar for browsing the Dasboard, profile, tables, maps is not accessible...
![capture](https://user-images.githubusercontent.com/39513151/48402882-b718f200-e752-11e8-95ed-52c7570b704d.JPG)

**Comment by Bloodcast69** [comment]
@SachienRaj 

This is the proper behavior. The sidenav is available only in the Pro version of MDBootstrap. 
MDB Angular Admin Free got something like sidenav, but it doesn't have every functionality like our Pro sidenav - so this sidenav from Admin free is hiding on the lower resolutions.

Best Regards,
Damian
